# Generated by Django 6.0.2 on 2026-02-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.FloatField(default=0)),
                ('stage', models.CharField(choices=[('group', 'Group Stage'), ('quarter', 'Quarter Final'), ('semi', 'Semi Final'), ('final', 'Final')], max_length=20)),
                ('group', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
